"""Build the EDJAS documentation site from this repository's canonical sources.

The site is generated by the project's own machinery: its pages extend the very
``base.html`` that the example reports use, so a documentation page and a generated
report are the same document with different content.

Prose is **composed, never copied**. Each page in ``pages.toml`` names the files it is
made from, and several of those live outside ``docs/`` -- the companion package's README
and ATTRIBUTION.md, the example specs' own comment headers, the function registry's
docstrings. Repository links are rewritten to site-relative ones on the way in, and an
unrecognised one fails the build under ``--strict``.

    python docs/build_site.py                 # build to docs/_site
    python docs/build_site.py --strict        # treat unmapped links as errors
    python docs/build_site.py --serve         # build, then serve on localhost:8000
"""

import argparse
import posixpath
import re
import shutil
import sys
import tomllib
from pathlib import Path
from xml.etree import ElementTree

import markdown
from markdown.extensions import Extension
from markdown.treeprocessors import Treeprocessor

DOCS = Path(__file__).resolve().parent
ROOT = DOCS.parent
IMAGES = ROOT / "images"

REPO = "https://github.com/holdenweb/edjas"
RAW = "https://raw.githubusercontent.com/holdenweb/edjas/main"

# Repository URLs that appear in the canonical Markdown, mapped to their place on the
# site. A value of None means "this is a real outbound link, leave it alone".
LINK_MAP = {
    f"{REPO}/blob/main/edjas-examples/README.md": "why.html",
    f"{REPO}/tree/main/edjas-examples": "gallery/index.html",
    f"{REPO}/blob/main/edjas-examples/src/edjas_examples/ATTRIBUTION.md": "colophon.html",
    f"{REPO}/blob/main/images/c4-context.svg": "architecture.html#c4-system-context",
    f"{REPO}/blob/main/images/c4-container.svg": "architecture.html#c4-container-diagram",
    f"{REPO}/blob/main/images/c4-component.svg": "architecture.html#c4-component-diagram",
    f"{REPO}/blob/main/images/internal-structure.svg": "architecture.html#internal-structure",
    f"{RAW}/images/example_workbook.png": "assets/example_workbook.png",
    REPO: None,
}

MARKDOWN_EXTENSIONS = ["tables", "fenced_code", "attr_list", "toc", "sane_lists"]


# --- link and heading rewriting ---------------------------------------------

def url_for(target, page_url):
    """Express site path ``target`` relative to the page living at ``page_url``.

    Everything on the site is linked relatively, so the output works unchanged from a
    ``file://`` preview, from a project page served under ``/edjas/``, and from a custom
    domain later. A root-relative link would break the middle case.
    """
    path, sep, frag = target.partition("#")
    if not path:
        return sep + frag
    rel = posixpath.relpath(path, posixpath.dirname(page_url) or ".")
    return rel + sep + frag


class _Links(Treeprocessor):
    """Rewrite repository links to their place on the site."""

    def __init__(self, md, page_url, problems):
        super().__init__(md)
        self.page_url = page_url
        self.problems = problems

    def run(self, root):
        for element, attribute in (("a", "href"), ("img", "src")):
            for node in root.iter(element):
                value = node.get(attribute)
                if value is not None:
                    node.set(attribute, self._rewrite(value))
        return root

    def _rewrite(self, href):
        if href in LINK_MAP:
            target = LINK_MAP[href]
            return href if target is None else url_for(target, self.page_url)
        if href.startswith("site:"):  # docs-only link, written depth-agnostically
            return url_for(href[len("site:"):], self.page_url)
        if href.startswith("#") or href.startswith("mailto:"):
            return href
        if href.startswith(("http://", "https://")):
            if href.startswith(REPO) or href.startswith(RAW):
                self.problems.append(f"{self.page_url}: unmapped repository link {href}")
            return href
        return href


class _Demote(Treeprocessor):
    """Shift headings down ``levels`` so a composed part nests under its host page."""

    def __init__(self, md, levels):
        super().__init__(md)
        self.levels = levels

    def run(self, root):
        for node in root.iter():
            if re.fullmatch(r"h[1-6]", node.tag or ""):
                node.tag = f"h{min(6, int(node.tag[1]) + self.levels)}"
        return root


class _SiteExtension(Extension):
    def __init__(self, page_url, problems, demote):
        super().__init__()
        self.page_url, self.problems, self.demote = page_url, problems, demote

    def extendMarkdown(self, md):
        if self.demote:
            md.treeprocessors.register(_Demote(md, self.demote), "edjas_demote", 4)
        md.treeprocessors.register(
            _Links(md, self.page_url, self.problems), "edjas_links", 3
        )


def render_markdown(text, page_url, problems, demote=0):
    """Convert Markdown to HTML, rewriting links relative to ``page_url``."""
    converter = markdown.Markdown(
        extensions=[*MARKDOWN_EXTENSIONS, _SiteExtension(page_url, problems, demote)]
    )
    return converter.convert(text)


# --- composing pages from canonical files ------------------------------------

def _strip_first_heading(text):
    lines = text.splitlines()
    for i, line in enumerate(lines):
        if line.startswith("# "):
            return "\n".join(lines[:i] + lines[i + 1:])
    return text


def comment_header(path):
    """Return the leading ``#`` comment block of a TOML file as Markdown.

    The seven example specs open with six to ten lines explaining the workbook's shape
    and why the spec reads it as it does. That prose exists nowhere else, so the gallery
    takes it straight from the spec rather than restating it.
    """
    lines = []
    for line in Path(path).read_text(encoding="utf-8").splitlines():
        if line.startswith("#"):
            lines.append(line.lstrip("#").strip())
        elif not lines:
            continue
        else:
            break
    return "\n".join(lines)


def spec_body(path):
    """Return a spec file with its leading comment block removed."""
    lines = Path(path).read_text(encoding="utf-8").splitlines()
    start = 0
    for i, line in enumerate(lines):
        if not line.startswith("#") and line.strip():
            start = i
            break
    return "\n".join(lines[start:]).strip()


def attribution_section(filename):
    """Return the ``ATTRIBUTION.md`` section documenting ``filename``, as Markdown.

    Raises if absent -- a bundled workbook with no attribution is a licensing problem,
    not a formatting one.
    """
    import edjas_examples

    text = (edjas_examples._PKG / "ATTRIBUTION.md").read_text(encoding="utf-8")
    for section in text.split("\n## ")[1:]:
        if filename in section.split("\n", 1)[0] or f"`{filename}`" in section:
            return "## " + section.strip()
    raise ValueError(f"no ATTRIBUTION.md section names {filename}")


def read_part(part, page_url, problems):
    """Render one manifest part to HTML."""
    path = (DOCS / part["file"]).resolve()
    if not path.is_file():
        raise FileNotFoundError(f"{page_url}: missing content file {path}")
    kind = part.get("as", "markdown")
    if kind == "code":
        body = path.read_text(encoding="utf-8").strip()
        lang = part.get("lang", path.suffix.lstrip("."))
        return render_markdown(f"```{lang}\n{body}\n```", page_url, problems)
    text = path.read_text(encoding="utf-8")
    if part.get("skip_first_heading"):
        text = _strip_first_heading(text)
    return render_markdown(text, page_url, problems, demote=part.get("demote", 0))


# --- inline SVG ---------------------------------------------------------------

def inline_svg(path, slug):
    """Return an SVG ready to be inlined alongside others in one document.

    Inline SVG is *document-scoped*: ids and CSS class names leak into the page and into
    each other. All four EDJAS diagrams define ``<marker id="arrow">`` and share class
    names (``.title``, ``.desc``, ``.hdr`` ...) with differing values, and one of them
    styles ``.line``, which would collide with the ledger row class in ``base.html``.
    So ids are namespaced and every selector is prefixed with the root id.
    """
    svg = Path(path).read_text(encoding="utf-8")
    svg = re.sub(r"<\?xml[^>]*\?>\s*", "", svg)

    # The enclosing <section> already uses `slug` as the page anchor, so the SVG root
    # needs an id of its own; two elements sharing one id is invalid and defeats the
    # in-page links.
    root_id = f"{slug}-diagram"

    ids = set(re.findall(r'\bid="([^"]+)"', svg))
    for name in ids:
        svg = re.sub(rf'\bid="{re.escape(name)}"', f'id="{root_id}-{name}"', svg)
        svg = svg.replace(f"url(#{name})", f"url(#{root_id}-{name})")

    def scope(match):
        css = match.group(1)
        scoped = re.sub(
            r"(^|\})\s*([^{}@]+?)\s*\{",
            lambda m: f"{m.group(1)} "
            + ", ".join(f"#{root_id} {sel.strip()}" for sel in m.group(2).split(","))
            + " {",
            css,
        )
        return f"<style>{scoped}</style>"

    svg = re.sub(r"<style>(.*?)</style>", scope, svg, flags=re.DOTALL)

    # Strip the sizing attributes from the root tag only: the diagrams also contain a
    # full-canvas background <rect width= height=> that must keep its dimensions.
    root_end = svg.index(">")
    root = re.sub(r'\s(?:width|height)="[^"]*"', "", svg[:root_end])
    root = root.replace("<svg", f'<svg id="{root_id}"', 1)
    return root + svg[root_end:]


def svg_description(path):
    """The ``<desc>`` text of a diagram, used as its figure caption."""
    text = Path(path).read_text(encoding="utf-8")
    match = re.search(r"<desc>(.*?)</desc>", text, flags=re.DOTALL)
    return " ".join(match.group(1).split()) if match else ""


# --- content generated from live objects --------------------------------------

_SITE_DATA = None


def site_data():
    """The site's own editorial tables, extracted from docs/site.xlsx by EDJAS.

    This is the site documenting itself with its own tool: the gallery cards and the
    summary tables below come out of a spreadsheet through an ordinary specification.
    Anything that belongs to *code* -- function names, signatures, command help -- is read
    from the live objects instead, so a reference page can never contradict the software.
    """
    global _SITE_DATA
    if _SITE_DATA is None:
        from edjas import read_spec

        workbook, spec = DOCS / "site.xlsx", DOCS / "site.toml"
        if not workbook.is_file():
            raise FileNotFoundError(
                f"{workbook} is missing; run `python scripts/create_site_workbook.py`"
            )
        _SITE_DATA = read_spec(str(workbook), str(spec))
    return _SITE_DATA


def function_reference():
    """The built-in functions: names and behaviour from the registry, prose from the site
    workbook. A built-in with no workbook row still appears, so nothing can go missing."""
    from edjas import functions as fns

    groups = {
        "records": "reshape", "columns": "reshape", "transpose": "reshape",
        "flatten": "reshape", "keys": "object", "values": "object",
        "items": "object", "invert": "object",
    }
    prose = {row["name"]: row for row in site_data()["functions"]}
    entries = []
    for name, func in fns.DEFAULT_FUNCTIONS.items():
        doc = (func.__doc__ or "").strip().split("\n\n")[0]
        row = prose.get(name, {})
        entries.append({
            "name": name,
            "group": groups.get(name, "coercion / formatting"),
            "doc": " ".join(doc.split()) or f"Applies {name} to every value.",
            "input": row.get("input", ""),
            "result": row.get("result", ""),
        })
    return entries


def spec_tables():
    """The two summary tables on the specification-language page, from site.xlsx."""
    data = site_data()
    return {"forms": data["forms"], "ref_kinds": data["ref_kinds"]}


def api_reference():
    """Signatures and docstrings for the public API, read by introspection."""
    import inspect

    import edjas

    out = []
    for name in ("read_spec", "render_report", "json_default"):
        obj = getattr(edjas, name)
        out.append({
            "name": name,
            "signature": f"{name}{inspect.signature(obj)}",
            "doc": _desugar(inspect.getdoc(obj) or ""),
        })
    return out


def _desugar(doc):
    """Turn the docstrings' reST flavouring into Markdown."""
    doc = re.sub(r":\w+:`~?([^`]+)`", r"`\1`", doc)
    return doc.replace("``", "`")


def cli_reference():
    """`--help` output for both console scripts."""
    import subprocess

    out = []
    for command in (["edjas", "--help"], ["edjas-examples", "--help"]):
        executable = ROOT / ".venv" / "bin" / command[0]
        if not executable.exists():
            continue
        result = subprocess.run(
            [str(executable), *command[1:]], capture_output=True, text=True
        )
        out.append({"command": command[0], "help": result.stdout.strip()})
    return out


DATA_PROVIDERS = {
    "functions": function_reference,
    "api": api_reference,
    "cli": cli_reference,
    "tables": spec_tables,
}


# --- the manifest --------------------------------------------------------------

def load_manifest():
    """Read ``pages.toml`` and expand the generated gallery pages."""
    import edjas_examples

    with open(DOCS / "pages.toml", "rb") as handle:
        raw = tomllib.load(handle)

    pages = [dict(page) for page in raw["page"]]
    gallery = raw.get("gallery")
    if gallery:
        for name in edjas_examples.EXAMPLES:
            notes = DOCS / gallery["notes_dir"] / f"{name}.md"
            pages.append({
                "url": gallery["url_pattern"].format(name=name),
                "title": name,
                "template": gallery["template"],
                "example": name,
                "parts": [{"file": str(notes.relative_to(DOCS))}] if notes.is_file() else [],
                "nav_group": "gallery/index.html",
            })
    return pages


def nav_items(pages):
    return [page for page in pages if page.get("nav")]


# --- building ------------------------------------------------------------------

def build_reports(out):
    """Render the seven example reports into the site, with consistent filenames."""
    import edjas_examples

    reports = out / "reports"
    reports.mkdir(parents=True, exist_ok=True)
    built = {}
    for name in edjas_examples.EXAMPLES:
        target = reports / f"{name}.html"
        edjas_examples.build(name, out=target)
        built[name] = f"reports/{name}.html"
    return built


def copy_assets(out):
    assets = out / "assets"
    assets.mkdir(parents=True, exist_ok=True)
    shutil.copy(DOCS / "assets" / "docs.css", assets / "docs.css")
    workbook_image = IMAGES / "example_workbook.png"
    if workbook_image.is_file():
        shutil.copy(workbook_image, assets / "example_workbook.png")


def build(out=None, strict=False):
    """Build the whole site into ``out`` (default ``docs/_site``)."""
    import edjas_examples
    import jinja2
    from importlib.resources import as_file

    out = Path(out) if out else DOCS / "_site"
    if out.exists():
        shutil.rmtree(out)
    out.mkdir(parents=True)

    pages = load_manifest()
    nav = nav_items(pages)
    problems = []

    with as_file(edjas_examples.TEMPLATES) as packaged:
        env = jinja2.Environment(
            loader=jinja2.ChoiceLoader([
                jinja2.FileSystemLoader(str(DOCS / "templates")),
                jinja2.FileSystemLoader(str(packaged)),
            ]),
            autoescape=jinja2.select_autoescape(["html", "xml"]),
            trim_blocks=True,
            lstrip_blocks=True,
        )

        reports = build_reports(out)
        copy_assets(out)

        for page in pages:
            html = render_page(env, page, pages, nav, reports, problems)
            destination = out / page["url"]
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_text(html, encoding="utf-8")

    (out / ".nojekyll").write_text("", encoding="utf-8")

    for problem in problems:
        print(f"  warning: {problem}", file=sys.stderr)
    if problems and strict:
        raise SystemExit(f"{len(problems)} link problem(s); --strict is set")
    print(f"built {len(pages)} pages and {len(reports)} reports into {out}")
    return out


def render_page(env, page, pages, nav, reports, problems):
    """Render one manifest page to HTML."""
    import edjas_examples

    url = page["url"]
    content = "".join(
        read_part(part, url, problems) for part in page.get("parts", [])
    )
    # `tail_parts` is prose that belongs *after* whatever the template generates in the
    # middle of the page -- the summary tables on the specification-language page, say.
    tail = "".join(
        read_part(part, url, problems) for part in page.get("tail_parts", [])
    )

    context = {
        "page": page,
        "pages": pages,
        "nav": nav,
        "content": content,
        "tail": tail,
        "url": lambda target: url_for(target, url),
        "reports": reports,
    }

    for key in page.get("data", []):
        context[key] = DATA_PROVIDERS[key]()

    if page.get("template") == "architecture.html":
        context["diagrams"] = [
            {
                "slug": slug,
                "title": title,
                "svg": inline_svg(IMAGES / f"{stem}.svg", slug),
                "desc": svg_description(IMAGES / f"{stem}.svg"),
            }
            for stem, slug, title in DIAGRAMS
        ]

    if "example" in page:
        name = page["example"]
        cfg = edjas_examples.EXAMPLES[name]
        spec = edjas_examples.DATA / cfg["spec"]
        context["example"] = {
            "name": name,
            "report": reports[name],
            "spec_name": cfg["spec"],
            "workbook": cfg["xlsx"],
            "intro": render_markdown(comment_header(spec), url, problems),
            "spec": spec_body(spec),
            "attribution": render_markdown(
                attribution_section(cfg["xlsx"]), url, problems, demote=1
            ),
            **cfg.get("context", {}),
        }

    if "gallery" in page.get("data", []) or page.get("template") == "gallery.html":
        context["examples"] = gallery_cards(url, problems)

    return env.get_template(page.get("template", "page.html")).render(**context)


DIAGRAMS = [
    ("c4-context", "c4-system-context", "System context"),
    ("c4-container", "c4-container-diagram", "Containers"),
    ("c4-component", "c4-component-diagram", "Components"),
    ("internal-structure", "internal-structure", "Internal structure"),
]


def gallery_cards(page_url, problems):
    """One card per example, with its editorial framing read from site.xlsx."""
    import edjas_examples

    from edjas import read_spec

    cards = []
    workbook = DOCS / "site.xlsx"
    editorial = {}
    if workbook.is_file():
        data = read_spec(str(workbook), str(DOCS / "site.toml"))
        editorial = {row["name"]: row for row in data["gallery"]}
    for name, cfg in edjas_examples.EXAMPLES.items():
        row = editorial.get(name, {})
        cards.append({
            "name": name,
            "url": url_for(f"gallery/{name}.html", page_url),
            "shape": row.get("shape", ""),
            "teaser": row.get("teaser", ""),
            "publisher": row.get("publisher", ""),
        })
    return cards


def main(argv=None):
    parser = argparse.ArgumentParser(
        prog="build_site", description="Build the EDJAS documentation site."
    )
    parser.add_argument("--out", default=None, help="output directory (default docs/_site)")
    parser.add_argument("--strict", action="store_true", help="fail on link problems")
    parser.add_argument("--serve", action="store_true", help="serve the site after building")
    parser.add_argument("--port", type=int, default=8000)
    args = parser.parse_args(argv)

    out = build(args.out, strict=args.strict)

    if args.serve:
        import functools
        import http.server

        handler = functools.partial(http.server.SimpleHTTPRequestHandler, directory=str(out))
        print(f"serving {out} on http://localhost:{args.port}/ -- Ctrl-C to stop")
        http.server.ThreadingHTTPServer(("", args.port), handler).serve_forever()


if __name__ == "__main__":
    main()
